// Assembles index.html from template.html + partials/*.html.
//
// Source of truth for the HTML structure is template.html (the page shell)
// and partials/*.html (one file per section: nav, hero, work, achievements,
// skills, about). Edit those, then run `node build.mjs` — or just run
// `node serve.mjs`, which rebuilds automatically on every request.
//
// index.html itself is generated output. Don't hand-edit it; edits will be
// overwritten on the next build.

import { readFile, writeFile } from 'fs/promises';
import { dirname, join } from 'path';
import { fileURLToPath, pathToFileURL } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));

const INCLUDE_RE = /<!--\s*@include:\s*([\w-]+)\s*-->/g;

export async function build() {
  const template = await readFile(join(__dirname, 'template.html'), 'utf8');

  const matches = [...template.matchAll(INCLUDE_RE)];
  const partials = await Promise.all(
    matches.map((m) =>
      readFile(join(__dirname, 'partials', `${m[1]}.html`), 'utf8'),
    ),
  );

  let i = 0;
  const html = template.replace(INCLUDE_RE, () => partials[i++].trimEnd());

  const banner =
    '<!-- AUTO-GENERATED by build.mjs from template.html + partials/*.html — do not hand-edit, run `node build.mjs` instead -->\n';

  await writeFile(join(__dirname, 'index.html'), banner + html);
  return html;
}

// Run directly (`node build.mjs`) vs. imported by serve.mjs
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  build()
    .then(() => console.log('Built index.html'))
    .catch((err) => {
      console.error('Build failed:', err);
      process.exit(1);
    });
}
